package com.mycompany.desafiomaven;


import java.awt.Desktop;
import java.lang.reflect.Field;
import java.net.URI;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.dom4j.Document;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;



import com.google.maps.GeoApiContext;
import com.google.maps.GeocodingApi;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.HashSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author johnc e gabriel
 */
public class DesafioUIL extends javax.swing.JFrame {

    /**
     * Creates new form DesafioUIL
     */
    public DesafioUIL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PPessoa = new javax.swing.JPanel();
        TxtNome = new javax.swing.JTextField();
        TxtTelefone = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        PEndereco = new javax.swing.JPanel();
        TxtCep = new javax.swing.JTextField();
        TxtEstado = new javax.swing.JTextField();
        TxtCidade = new javax.swing.JTextField();
        TxtBairro = new javax.swing.JTextField();
        TxtRua = new javax.swing.JTextField();
        TxtNumero = new javax.swing.JTextField();
        TxtComplemento = new javax.swing.JTextField();
        BtnAtualizarE = new javax.swing.JButton();
        BtnDeletarE = new javax.swing.JButton();
        BtnAnteriorE = new javax.swing.JButton();
        BtnProximoE = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnAdicionarE = new javax.swing.JButton();
        BtnLimparE = new javax.swing.JButton();
        TxtTipo = new javax.swing.JTextField();
        BtnPesquisarE = new javax.swing.JButton();
        TxtCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BtnAdicionarP = new javax.swing.JButton();
        BtnAtualizarP = new javax.swing.JButton();
        BtnDeletarP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnPesquisarP = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        BtnLimparPessoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEnd = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TxtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtTelefoneFocusLost(evt);
            }
        });

        TxtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtEmailFocusLost(evt);
            }
        });

        PEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TxtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCepFocusLost(evt);
            }
        });
        TxtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCepActionPerformed(evt);
            }
        });

        TxtEstado.setEditable(false);
        TxtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEstadoActionPerformed(evt);
            }
        });

        TxtCidade.setEditable(false);

        TxtBairro.setEditable(false);

        TxtRua.setEditable(false);

        BtnAtualizarE.setText("Atualizar Endereço");
        BtnAtualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarEActionPerformed(evt);
            }
        });

        BtnDeletarE.setText("Deletar Endereço");
        BtnDeletarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarEActionPerformed(evt);
            }
        });

        BtnAnteriorE.setText("< Anterior");

        BtnProximoE.setText("Proximo >");

        jLabel5.setText("Tipo");

        jLabel6.setText("Cep");

        jLabel7.setText("Estado");

        jLabel8.setText("Cidade");

        jLabel9.setText("Bairro");

        jLabel10.setText("Rua");

        jLabel11.setText("Número");

        jLabel12.setText("Complemento");

        BtnAdicionarE.setText("Adicionar Endereço");
        BtnAdicionarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarEActionPerformed(evt);
            }
        });

        BtnLimparE.setText("Limpar");
        BtnLimparE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparEActionPerformed(evt);
            }
        });

        BtnPesquisarE.setText("Pesquisar Endereço");
        BtnPesquisarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarEActionPerformed(evt);
            }
        });

        jLabel14.setText("Codigo");

        javax.swing.GroupLayout PEnderecoLayout = new javax.swing.GroupLayout(PEndereco);
        PEndereco.setLayout(PEnderecoLayout);
        PEnderecoLayout.setHorizontalGroup(
            PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEnderecoLayout.createSequentialGroup()
                        .addComponent(BtnAnteriorE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnLimparE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnProximoE))
                    .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PEnderecoLayout.createSequentialGroup()
                            .addComponent(BtnPesquisarE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnAdicionarE))
                        .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PEnderecoLayout.createSequentialGroup()
                                .addComponent(BtnDeletarE, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnAtualizarE, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PEnderecoLayout.createSequentialGroup()
                                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PEnderecoLayout.setVerticalGroup(
            PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAnteriorE)
                    .addComponent(BtnLimparE)
                    .addComponent(BtnProximoE))
                .addGap(18, 18, 18)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdicionarE)
                    .addComponent(BtnPesquisarE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDeletarE)
                    .addComponent(BtnAtualizarE))
                .addContainerGap())
        );

        BtnAdicionarP.setText("Adicionar Pessoa");
        BtnAdicionarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarPActionPerformed(evt);
            }
        });

        BtnAtualizarP.setText("Atualizar Pessoa");
        BtnAtualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarPActionPerformed(evt);
            }
        });

        BtnDeletarP.setText("Deletar Pessoa");
        BtnDeletarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarPActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Telefone");

        jLabel4.setText("E-mail");

        BtnPesquisarP.setText("Pesquisar Pessoa");
        BtnPesquisarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarPActionPerformed(evt);
            }
        });

        jLabel13.setText("ID");

        BtnLimparPessoa.setText("Limpar");
        BtnLimparPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparPessoaActionPerformed(evt);
            }
        });

        tableEnd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Endereços"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEnd.setFocusable(false);
        tableEnd.setInheritsPopupMenu(true);
        tableEnd.setRequestFocusEnabled(false);
        tableEnd.setVerifyInputWhenFocusTarget(false);
        tableEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEndMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEnd);

        javax.swing.GroupLayout PPessoaLayout = new javax.swing.GroupLayout(PPessoa);
        PPessoa.setLayout(PPessoaLayout);
        PPessoaLayout.setHorizontalGroup(
            PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPessoaLayout.createSequentialGroup()
                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PPessoaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PPessoaLayout.createSequentialGroup()
                                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(TxtEmail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPessoaLayout.createSequentialGroup()
                                .addComponent(BtnPesquisarP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnAtualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PPessoaLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNome)
                                    .addComponent(TxtId)))
                            .addGroup(PPessoaLayout.createSequentialGroup()
                                .addComponent(BtnAdicionarP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(BtnDeletarP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PPessoaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtTelefone))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPessoaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtnLimparPessoa)
                                .addGap(92, 92, 92))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PPessoaLayout.setVerticalGroup(
            PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPessoaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPessoaLayout.createSequentialGroup()
                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimparPessoa)
                        .addGap(14, 14, 14)
                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnPesquisarP)
                            .addComponent(BtnAtualizarP))
                        .addGap(18, 18, 18)
                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDeletarP)
                            .addComponent(BtnAdicionarP))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(PPessoaLayout.createSequentialGroup()
                        .addComponent(PEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeletarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarPActionPerformed
        //BOTÃO DELETA PESSOA
        Validacao(pessoa,"deletagem");
        if (Erro.getErro())
           javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else{
            pessoa.setId(TxtId.getText());
            ALDAL.delete(pessoa);
            if (Erro.getErro())
            JOptionPane.showMessageDialog(null,Erro.getMens());
            else{
                Limpar("P");
                JOptionPane.showMessageDialog(null,"Dados Deletados com sucesso!");
            }   
        }
    }//GEN-LAST:event_BtnDeletarPActionPerformed

    private void BtnAtualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarPActionPerformed
        //BOTÃO ATUALIZAR PESSOA
        Validacao(pessoa,"atualizacao");
        if (Erro.getErro()) {
            javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        } else {
            pessoa.setId(TxtId.getText());
            Pessoa dados = new Pessoa();
            dados.setNome(TxtNome.getText());
            dados.setTelefone(TxtTelefone.getText());
            dados.setEmail(TxtEmail.getText());
            ALDAL.update(dados, pessoa);
            if (Erro.getErro())
                JOptionPane.showMessageDialog(null, Erro.getMens());
            else {
               JOptionPane.showMessageDialog(null, "Dados Atualizados com sucesso!");
            } 
        }
    }//GEN-LAST:event_BtnAtualizarPActionPerformed

    private void BtnAdicionarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarPActionPerformed
        // BOTÃO ADICIONAR PESSOA
        // *SÓ PODE FAZER O INSERT COM ENDEREÇO
         Validacao(endereco,"adicao");
                if (Erro.getErro()) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Necessario preencher o formulario de ENDERECO para realizar o cadastro!");}
                else{
                    AddEndereco();
                    if (Erro.getErro()) {
                            javax.swing.JOptionPane.showMessageDialog(null, Erro.getMens());}
                        else {
                            
                            Ler(pessoa);
                            ALDAL.set(pessoa);
                            if (Erro.getErro())
                               JOptionPane.showMessageDialog(null, Erro.getMens());
                            else {
                               JOptionPane.showMessageDialog(null, "Dados Salvos com sucesso!");
                           }
                       }
                }
    }//GEN-LAST:event_BtnAdicionarPActionPerformed

    private void BtnDeletarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarEActionPerformed
        //BOTÃO DELETAR ENDERECO
         Validacao(endereco,"deletagem");
        if (Erro.getErro())
           javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else{
            endereco.setCodigo(TxtId.getText());
            ALDAL.delete(pessoa);
            if (Erro.getErro())
            JOptionPane.showMessageDialog(null,Erro.getMens());
            else{
                Limpar("P");
                JOptionPane.showMessageDialog(null,"Dados Deletados com sucesso!");
            }
        }     
    }//GEN-LAST:event_BtnDeletarEActionPerformed

    private void BtnAtualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarEActionPerformed
        //BOTÃO ATUALIZAR ENDERECO
         Validacao(endereco,"atualizacao");
        if (Erro.getErro())
           javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else{
            endereco.setCodigo(TxtCodigo.getText());
           Endereco dados = new Endereco();
           dados.setCodigo(TxtCodigo.getText());
           dados.setTipo(TxtTipo.getText());
           dados.setCep(TxtCep.getText());
           dados.setEstado(TxtEstado.getText());
           dados.setCidade(TxtCidade.getText());
           dados.setBairro(TxtBairro.getText());
           dados.setRua(TxtRua.getText());
           dados.setNumero(TxtNumero.getText());
           dados.setComplemento(TxtComplemento.getText());

           ALDAL.update(dados,pessoa);
           if (Erro.getErro())
               JOptionPane.showMessageDialog(null,Erro.getMens());
           else{
               JOptionPane.showMessageDialog(null,"Dados Atualizados com sucesso!");
           }
        }
    }//GEN-LAST:event_BtnAtualizarEActionPerformed

    private void BtnAdicionarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarEActionPerformed
        //BOTÃO ADICIONAR ENDEREÇO
         AddEndereco();
    }//GEN-LAST:event_BtnAdicionarEActionPerformed

    private void AddEndereco(){
        Validacao(endereco,"adicao");
        if (Erro.getErro())
           javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else{
            Ler(endereco);
            ALDAL.set(endereco);
            if (Erro.getErro())
                JOptionPane.showMessageDialog(null,Erro.getMens());
            else
                JOptionPane.showMessageDialog(null,"Dados Salvos com sucesso!");
        }
    }
    
    private void BtnPesquisarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarPActionPerformed
        //BOTÃO PESQUISA PESSOA
        pessoa.setId(TxtId.getText());
        pessoa.setNome(TxtNome.getText());
        pessoa.setTelefone(TxtTelefone.getText());
        pessoa.setEmail(TxtEmail.getText());
        
        DefaultTableModel model = (DefaultTableModel) tableEnd.getModel();

        
        ALDAL.get(pessoa);
        if (Erro.getErro())
            JOptionPane.showMessageDialog(null,Erro.getMens());
        else
        {
            TxtId.setText(pessoa.getId());
            TxtNome.setText(pessoa.getNome());
            TxtTelefone.setText(pessoa.getTelefone());
            TxtEmail.setText(pessoa.getEmail());
        };
        
       Endereco end = new Endereco();
       end.setId(pessoa.getId());
       ArrayList<Endereco> ends = ALDAL.get2(end);
        
        for(Endereco e : ends)
        {
            model.addRow(new Object[]{e.getRua() + ", " + e.getNumero() + " - " + e.getBairro() + ", " +e.getCidade() + " - " + e.getCep()});
        }
        
    }//GEN-LAST:event_BtnPesquisarPActionPerformed

    private void TxtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEstadoActionPerformed

    private void BtnLimparPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparPessoaActionPerformed
        // BOTÃO LIMPAR PESSOA
        Limpar(pessoa);
    }//GEN-LAST:event_BtnLimparPessoaActionPerformed

    private void BtnPesquisarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarEActionPerformed
        // BOTÃO PESQUISAR ENDERECO
         Validacao(endereco,"pesquisa");
        if (Erro.getErro())
           javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        else{
            Ler(endereco);
            ALDAL.get(endereco);
            if (Erro.getErro())
                JOptionPane.showMessageDialog(null,Erro.getMens());
            else
                Mostrar(endereco);
        }
    }//GEN-LAST:event_BtnPesquisarEActionPerformed

    private void BtnLimparEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparEActionPerformed
        //BOTÃO LIMPAR ENDERECO
        Limpar(endereco);
    }//GEN-LAST:event_BtnLimparEActionPerformed

    private void TxtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCepActionPerformed
        //Texto CEP
    }//GEN-LAST:event_TxtCepActionPerformed

    private void TxtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCepFocusLost
        // TODO add your handling code here:
        BuscarCep(TxtCep.getText());
        if (Erro.getErro())
                JOptionPane.showMessageDialog(null,Erro.getMens());
    }//GEN-LAST:event_TxtCepFocusLost

    private void TxtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtTelefoneFocusLost
        // TODO add your handling code here:
        if (validarTel(TxtTelefone.getText())==true || TxtTelefone.getText().equals("")){
            
        }
        else
            JOptionPane.showMessageDialog(null, "O telefone é inválido.");
    }//GEN-LAST:event_TxtTelefoneFocusLost

    private void TxtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtEmailFocusLost
        // TODO add your handling code here:
        if (validarEmail(TxtEmail.getText())==true || TxtEmail.getText().equals("")){
            
        }
        else
            JOptionPane.showMessageDialog(null, "O e-mail é inválido.");
    }//GEN-LAST:event_TxtEmailFocusLost

    private void tableEndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEndMouseClicked
        int rowI = tableEnd.rowAtPoint(evt.getPoint());
        DesafioUIL endView = new DesafioUIL();
        endView.setText("a");
    }//GEN-LAST:event_tableEndMouseClicked
/**/
    
    private void BuscarCep(String _cep){
        try{
            TxtEstado.setText("");
            TxtCidade.setText("");
            TxtBairro.setText("");
            TxtRua.setText("");
            URL url = new URL("https://viacep.com.br/ws/"+_cep+"/xml/");
            SAXReader xml = new SAXReader();
            Document documento = xml.read(url);
            Element root = documento.getRootElement();
            
            for (Iterator<Element> it = root.elementIterator(); it.hasNext();) {
                Element element = it.next();
                if(element.getQualifiedName().equals("bairro")){
                    TxtBairro.setText(element.getText());
                }
                if(element.getQualifiedName().equals("uf")){
                    TxtEstado.setText(element.getText());
                }
                if(element.getQualifiedName().equals("localidade")){
                    TxtCidade.setText(element.getText());
                }
                if(element.getQualifiedName().equals("logradouro")){
                    TxtRua.setText(element.getText());
                }
                if(element.getQualifiedName().equals("erro")){
                    String erro = element.getText();
                    if(erro.equals("true"))
                        JOptionPane.showMessageDialog(null,"Cep não encontrado!");
                        
                }
            }    
        } catch (Exception e){
            System.out.println(e);
        JOptionPane.showMessageDialog(null,"Cep não encontrado!");
        }
    }
    
    private void Link(String site){
        Desktop desktop = Desktop.getDesktop();
        try{
            URI uri =  new URI(site);
            desktop.browse(uri);
        } catch (Exception e){
            System.out.println(e);
        }
    }
    
    private void Validacao(Object obj, String tipoCrud){
        if(obj == pessoa){
            if(tipoCrud == "pesquisa"){
                if(TxtId.getText().equals("")&&
                        TxtNome.getText().equals("")&&
                        TxtTelefone.getText().equals("")&&
                        TxtEmail.getText().equals("")){
                    Erro.setErro(true,"Obrigatorio digitar no minimo 1 CAMPO de "+obj.getClass().getSimpleName() +" para realizar a "+tipoCrud); return;                    
                }
                else
                    Erro.setErro(false,""); return;                    

            }
            else if(tipoCrud == "adicao"||tipoCrud=="atualizacao"){
                if(TxtNome.getText().equals("")||
                        TxtTelefone.getText().equals("")||
                        TxtEmail.getText().equals("")){
                    Erro.setErro(true,"Obrigatorio digitar TODOS OS CAMPOS de "+obj.getClass().getSimpleName() +" para realizar a "+tipoCrud); return;
                }
                else
                    Erro.setErro(false,""); return; 
            }
            else if(tipoCrud == "deletagem"){
                if(TxtId.getText().equals("")){
                    Erro.setErro(true,"Obrigatorio digitar O ID de "+obj.getClass().getSimpleName() +" para realizar a "+tipoCrud); return;
                }
                else
                    Erro.setErro(false,""); return; 
            }
        }
        else if(obj == endereco){
            if(tipoCrud == "pesquisa"){
                if(TxtTipo.getText().equals("")&&
                        TxtCep.getText().equals("")&&
                        TxtEstado.getText().equals("")&&
                        TxtCidade.getText().equals("")&&
                        TxtBairro.getText().equals("")&&
                        TxtRua.getText().equals("")&&
                        TxtNumero.getText().equals("")&&
                        TxtComplemento.getText().equals("")){
                    Erro.setErro(true,"Obrigatorio digitar no minimo 1 CAMPO de "+obj.getClass().getSimpleName() +" para realizar a "+tipoCrud); return;
                }
                else
                    Erro.setErro(false,""); return; 
            }
            else if(tipoCrud == "adicao"||tipoCrud=="atualizacao"){
                if(TxtCodigo.getText().equals("")||
                        TxtTipo.getText().equals("")||
                        TxtCep.getText().equals("")||
                        TxtEstado.getText().equals("")||
                        TxtCidade.getText().equals("")||
                        TxtBairro.getText().equals("")||
                        TxtRua.getText().equals("")||
                        TxtNumero.getText().equals("")||
                        TxtComplemento.getText().equals("")){
                    Erro.setErro(true,"Obrigatorio digitar TODOS OS CAMPOS de "+obj.getClass().getSimpleName() +" para realizar a "+tipoCrud); return;
                }
                else
                    Erro.setErro(false,""); return; 
            }
            else if(tipoCrud == "deletagem"){
                if(TxtCodigo.getText().equals("")){
                    Erro.setErro(true,"Obrigatorio digitar O ID de "+obj.getClass().getSimpleName() +" para realizar a "+tipoCrud); return;
                }
                else
                    Erro.setErro(false,""); return; 
            }
        }
    }
    private void Limpar(Object obj){
        
        if(obj == pessoa){
            TxtId.setText("");
            TxtNome.setText("");
            TxtTelefone.setText("");
            TxtEmail.setText("");
        }
        else if(obj == endereco){
            //CbTipo.setName("");
            TxtId.setText("");
            TxtCodigo.setText("");
            TxtTipo.setText("");
            TxtCep.setText("");
            TxtEstado.setText("");
            TxtCidade.setText("");
            TxtBairro.setText("");
            TxtRua.setText("");
            TxtNumero.setText("");
            TxtComplemento.setText("");
        }
    }
    
     private void Mostrar(Object obj){
        //Mostra os valores setados no obj
        
        if(obj == pessoa){
            TxtId.setText(pessoa.getId());
            TxtNome.setText(pessoa.getNome());
            TxtTelefone.setText(pessoa.getTelefone());
            TxtEmail.setText(pessoa.getEmail());
        }
        else if(obj == endereco){
            //CbTipo.setName("");
            TxtId.setText(endereco.getId());
            TxtCodigo.setText(endereco.getCodigo());
            TxtTipo.setText(endereco.getTipo());
            TxtCep.setText(endereco.getCep());
            TxtEstado.setText(endereco.getEstado());
            TxtCidade.setText(endereco.getCidade());
            TxtBairro.setText(endereco.getBairro());
            TxtRua.setText(endereco.getRua());
            TxtNumero.setText(endereco.getNumero());
            TxtComplemento.setText(endereco.getComplemento());
        }
    }
    
     private void Ler(Object obj){
        //Le os valores nos txt e seta no obj
        
            if(obj == pessoa){
                pessoa.setId(TxtId.getText());
                pessoa.setNome(TxtNome.getText());
                pessoa.setTelefone(TxtTelefone.getText());
                pessoa.setEmail(TxtEmail.getText());
            }
            else if(obj == endereco){
                endereco.setCodigo(TxtCodigo.getText());
                endereco.setId(TxtId.getText());
                endereco.setTipo(TxtTipo.getText());
                endereco.setCep(TxtCep.getText());
                endereco.setEstado(TxtEstado.getText());
                endereco.setCidade(TxtCidade.getText());
                endereco.setBairro(TxtBairro.getText());
                endereco.setRua(TxtRua.getText());
                endereco.setNumero(TxtNumero.getText());
                endereco.setComplemento(TxtComplemento.getText());
            }
        
    }
     
     private static boolean validarEmail(String email)
     {
        String emailRegex = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        //Pattern pattern = Pattern.compile(emailRegex);
        return matcher.matches();
         
     }
     
     private static boolean validarTel(String telefone)
     {
        String telRegex = "^\\d{2}\\s?\\d{8,9}$";
        Pattern pattern = Pattern.compile(telRegex);
        Matcher matcher = pattern.matcher(telefone);
        return matcher.matches();
     }
    
     
     
    private Pessoa pessoa = new Pessoa();
    private Endereco endereco = new Endereco();
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesafioUIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesafioUIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesafioUIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesafioUIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesafioUIL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionarE;
    private javax.swing.JButton BtnAdicionarP;
    private javax.swing.JButton BtnAnteriorE;
    private javax.swing.JButton BtnAtualizarE;
    private javax.swing.JButton BtnAtualizarP;
    private javax.swing.JButton BtnDeletarE;
    private javax.swing.JButton BtnDeletarP;
    private javax.swing.JButton BtnLimparE;
    private javax.swing.JButton BtnLimparPessoa;
    private javax.swing.JButton BtnPesquisarE;
    private javax.swing.JButton BtnPesquisarP;
    private javax.swing.JButton BtnProximoE;
    private javax.swing.JPanel PEndereco;
    private javax.swing.JPanel PPessoa;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JTextField TxtCep;
    private javax.swing.JTextField TxtCidade;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtComplemento;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEstado;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtRua;
    private javax.swing.JTextField TxtTelefone;
    private javax.swing.JTextField TxtTipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableEnd;
    // End of variables declaration//GEN-END:variables

    private void setText(String a) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
